# Generated by Django 4.2.4 on 2023-09-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postCategory',
            field=models.ManyToManyField(to='news.category'),
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
